### PR TITLE
Fix for PR 194.  Fix SetCurrentTextString when textbox is not grayed out.

### LINKED ISSUE #194: SetCurrentTextString() in EditBox from SimpleUiToolkit not working bug
This function leaves the box empty ant text is never set. Just add this:

StrnCpyS(this->m_EditBoxDisplayText, sizeof(this->m_EditBoxDisplayText) / sizeof(CHAR16), NewTextString, (UIT_EDITBOX_MAX_STRING_LENGTH - 1));

after StrnCpyS (this->m_EditBoxText...

on the line  322 in function SetCurrentTextString() in  MsGraphics\Library\SimpleUIToolKit\EditBox.c to make it work.

### PR DESCRIPTION
**Pull request by mikeytdisco**
# Preface

Fixes #194  

## Description

The EditBox doesn't display initial text when not grayed out.

- [x] Impacts functionality?
- [ ] Impacts security?
- [ ] Breaking change?
- [ ] Includes tests?
- [ ] Includes documentation?

## Integration Instructions

N/A

### CODE REVIEW

**Review by makubacki — APPROVED** [review]

**Review by apop5 — APPROVED** [review]

File: MsGraphicsPkg/Library/SimpleUIToolKit/EditBox.c [hunk 1]
```diff
@@ -319,6 +320,13 @@ SetCurrentTextString (
   } else {
     RenderRequired = 0 != StrnCmp (this->m_EditBoxText, NewTextString, UIT_EDITBOX_MAX_STRING_LENGTH - 1);
     StrnCpyS (this->m_EditBoxText, sizeof (this->m_EditBoxText)/sizeof (CHAR16), NewTextString, (UIT_EDITBOX_MAX_STRING_LENGTH - 1));
+    if (UIT_EDITBOX_TYPE_PASSWORD != this->m_Type) {
+      StrnCpyS (this->m_EditBoxDisplayText, sizeof (this->m_EditBoxDisplayText)/sizeof (CHAR16), NewTextString, (UIT_EDITBOX_MAX_STRING_LENGTH - 1));
+    } else {
+      MaxLen = MIN(sizeof(this->m_EditBoxDisplayText), NewTextLen * sizeof (CHAR16));
```
Comment (apop5) [inline MsGraphicsPkg/Library/SimpleUIToolKit/EditBox.c]:
```suggestion
      MaxLen = MIN (sizeof (this->m_EditBoxDisplayText), NewTextLen * sizeof (CHAR16));

```
